version: '3.8'
services:
  tomcat:
    build: .
    container_name: my-ecommerce-app
    environment:
      CATALINA_HOME: /usr/local/tomcat
      RAZORPAY_API_KEY: rzp_test_yVDgRhYuDx3lXm
      RAZORPAY_API_SECRET: jq8wpYMxqhbZbgvy3K6nyigh
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
     
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/my.cnf  # Mount custom my.cnf file
volumes:
  db-data:

