/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-06-11 09:43:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.demo.User;

public final class addProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/../components/common.jsp", Long.valueOf(1717741690697L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("com.demo.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/other/stylesheet.css?modified=20012009\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write(" <script src=\"https://kit.fontawesome.com/c13edee66d.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write(" \r\n");
      out.write(" ");
      out.write("\r\n");
      out.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/other/addProduct.css\" >\r\n");

   User user = (User)session.getAttribute("current-user");
    if(user == null)
    {
    	// send msg
    	response.sendRedirect("login.jsp");
    	return;
    }else if(user.getRole() == "customer"){
    	// send msg
    	response.sendRedirect("login.jsp");
    	return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./admin.jsp", out, false);
      out.write("\r\n");
      out.write("  <div class=\"container-fluid\" id=\"addProduct\">\r\n");
      out.write("       <div class=\"d-flex flex-column align-items-center \">\r\n");
      out.write("            <div class=\"d-flex align-items-center mt-3 ms-2\">\r\n");
      out.write("                <h3>Products</h3>\r\n");
      out.write("                <span class=\"text-secondary ms-3\">Add New Product</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\" pt-3 p-4 mt-4\" id=\"addProductFormDiv\">\r\n");
      out.write("               <form action=\"\" method=\"\">\r\n");
      out.write("                  <div class=\"mb-3\" >\r\n");
      out.write("                    <label for=\"exampleInputProductName\" class=\"form-label\">Product name</label>\r\n");
      out.write("                     <input type=\"text\" class=\"form-control \" name=\"product_name\" id=\"exampleInputProductName\" aria-describedby=\"productName\" placeholder=\"Enter product name\" required>\r\n");
      out.write("                     <div id=\"error-massage\" class=\"form-text d-none\">Please enter the name of product</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                   <div class=\"mb-3 row justify-content-start double-div \">\r\n");
      out.write("                        <div class=\"col-sm-12 col-md-6\">\r\n");
      out.write("                            <label for=\"productPrice\" class=\"form-label\">Price</label>\r\n");
      out.write("                            <input type=\"text\" id=\"productPrice\"name=\"product_price\" class=\"form-control double-input\" placeholder=\"Enter the price\" aria-describedby=\"productPrice\"  required>\r\n");
      out.write("                            <div id=\"error-massage\" class=\"form-text d-none\">Please enter the price of product</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-12 col-md-6 \"> \r\n");
      out.write("                            <label for=\"productCategory\" class=\"form-label\">Category</label>\r\n");
      out.write("                            <input type=\"text\" id=\"productCategory\" name=\"product_category\" class=\"form-control double-input\" aria-describedby=\"productCategory\"  placeholder=\"Enter the category\" required>\r\n");
      out.write("                            <div id=\"error-massage\" class=\"form-text d-none\">Please enter the Category of product</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   \r\n");
      out.write("                    <div class=\"mb-3 row  justify-content-start double-div\">\r\n");
      out.write("                       <div class=\"col-sm-12 col-md-6\">\r\n");
      out.write("                            <label for=\"productForGender\" class=\"form-label\">Gender</label>\r\n");
      out.write("                            <select class=\"form-select form-control double-input\" id=\"productForGender\" name=\"productForGender\"  aria-label=\"productForGender\" required>\r\n");
      out.write("                                <option selected>Select gender</option>\r\n");
      out.write("                                <option value=\"1\">Male</option>\r\n");
      out.write("                                <option value=\"2\">Female</option>\r\n");
      out.write("                                <option value=\"3\">Other</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                            <div id=\"error-massage\" class=\"form-text d-none\">Please select the gender</div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                       <div class=\"col-sm-12 col-md-6  \">\r\n");
      out.write("                            \r\n");
      out.write("                            <label for=\"productColor\" class=\"form-label\">Color</label>\r\n");
      out.write("                            <input type=\"text\" id=\"productColor\"class=\"form-control double-input\" name=\"product_color\" aria-describedby=\"productColor\"  placeholder=\"Enter the color\" required>\r\n");
      out.write("                            <div id=\"error-massage\" class=\"form-text d-none\">Please enter the color of product</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-3 row  justify-content-start double-div\">\r\n");
      out.write("                        <div class=\"col-sm-12 col-md-6  \">\r\n");
      out.write("                            <label for=\"productSize\" class=\"form-label\">Size</label>\r\n");
      out.write("                            <input type=\"text\" id=\"productSize\" class=\"form-control double-input\" name=\"product_size\" placeholder=\"Enter the size\" aria-describedby=\"productSize\"  required>\r\n");
      out.write("                            <div id=\"error-massage\" class=\"form-text d-none\">Please enter the size of product</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-12 col-md-6 \"> \r\n");
      out.write("                            <label for=\"productQty\" class=\"form-label\">Quntity</label>\r\n");
      out.write("                            <input type=\"text\" id=\"productQty\"class=\"form-control double-input\" name=\"product_qty\" aria-describedby=\"productQty\"  placeholder=\"Enter the quntity\" required>\r\n");
      out.write("                            <div id=\"error-massage\" class=\"form-text d-none\">Please enter the quntity of product</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"mb-3 \">\r\n");
      out.write("                        <label for=\"productDescription\">Description</label>\r\n");
      out.write("                        <textarea id=\"productDescription\" class=\"form-control\" rows=\"4\" name=\"product_desc\" placeholder=\"Enter product description\"></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label for=\"productImage\">Upload Image</label>\r\n");
      out.write("                        <input type=\"file\" id=\"productImage\" name=\"image\" accept=\"image/*\" required>\r\n");
      out.write("                        <div id=\"error-massage \" class=\"form-text d-none\">Please choose product image</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   <div class=\"mb-3 d-flex justify-content-center align-items-center\">\r\n");
      out.write("                     <button type=\"submit\" class=\"btn btn-dark w-50 mt-3\" id=\"addProduct\">Submit</button>\r\n");
      out.write("                   </div>\r\n");
      out.write("               </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
