/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-06-11 09:39:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.demo.User;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/../components/common.jsp", Long.valueOf(1717741690697L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("com.demo.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/other/stylesheet.css?modified=20012009\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write(" <script src=\"https://kit.fontawesome.com/c13edee66d.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write(" \r\n");
      out.write(" ");
      out.write("\r\n");
      out.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/other/admin.css\" >\r\n");

   User user = (User)session.getAttribute("current-user");
    if(user == null)
    {
    	// send msg
    	response.sendRedirect("login.jsp");
    	return;
    }else if(user.getRole() == "customer"){
    	// send msg
    	response.sendRedirect("login.jsp");
    	return;
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark  border-bottom border-light-subtle\">\r\n");
      out.write("    <div class=\"container-fluid  \">\r\n");
      out.write("      <!-- btn-toggler offcanvas -->\r\n");
      out.write("      <div class=\"me-4 me-lg-0\">\r\n");
      out.write("        <button class=\"navbar-toggler\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#bd-sidebar\" aria-controls=\"bd-sidebar\" >\r\n");
      out.write("          <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("        <a class=\"navbar-brand fw-bold text-uppercase ms-0\" href=\"#\">\r\n");
      out.write("           Admin Panel\r\n");
      out.write("        </a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContentAdmin\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("          <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"collapse navbar-collapse my-4 my-lg-0 \" id=\"navbarSupportedContentAdmin\" >\r\n");
      out.write("        <form action=\"#\" class=\"me-2 ms-auto\">\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"input-group \">\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"Recipient's username\" aria-label=\"Recipient's username\" aria-describedby=\"button-addon2\">\r\n");
      out.write("            <button class=\"btn btn-outline-secondary\" type=\"button\" id=\"button-addon2\">\r\n");
      out.write("              <i class=\"fa-solid fa-magnifying-glass\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <div class=\"dropdown admin-navbar-dropdown mt-2 mt-lg-0 \">\r\n");
      out.write("          <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"32\" fill=\"currentColor\" class=\"bi bi-person dropdown-toggle me-3\"\r\n");
      out.write("          style=\"color: whitesmoke;\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" viewBox=\"0 0 16 16\">\r\n");
      out.write("            <path d=\"M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z\"/>\r\n");
      out.write("          </svg>\r\n");
      out.write("          <ul class=\"dropdown-menu\" id=\"admin-dropdown-menu\">\r\n");
      out.write("            <li>\r\n");
      out.write("               <button class=\"dropdown-item\" type=\"submit\">Logout</button>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"login.jsp\">Login</a></li>\r\n");
      out.write("      \r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- sidebar offcanvas -->\r\n");
      out.write("\r\n");
      out.write("<aside>\r\n");
      out.write("    <div class=\"offcanvas offcanvas-start text-bg-dark sidebar \" tabindex=\"-1\" id=\"bd-sidebar\" aria-labelledby=\"bd-sidebarLabel\">\r\n");
      out.write("      <div class=\"offcanvas-header\">\r\n");
      out.write("        <button type=\"button \" class=\"btn-close d-lg-none d-block  text-bg-danger text-danger\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"offcanvas-body p-0\">\r\n");
      out.write("        <nav class=\"navbar-dark \">\r\n");
      out.write("          <ul class=\"navbar-nav\">\r\n");
      out.write("            <li class=\"mt-2\">\r\n");
      out.write("              <a href=\"#\" class=\"nav-link px-3 active\">\r\n");
      out.write("                <span class=\"me-2\"><i class=\"fa-solid fa-chart-line\"></i></span> \r\n");
      out.write("                <span>Dashboard</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"mt-2\">\r\n");
      out.write("              <a href=\"#\" class=\"nav-link px-3 active\">\r\n");
      out.write("                <span class=\"me-2 text-light\"><i class=\"fa-solid fa-boxes-stacked\"></i></span> \r\n");
      out.write("                <span>Products</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"mt-2\">\r\n");
      out.write("              <a href=\"#\" class=\"nav-link px-3 active\">\r\n");
      out.write("                <span class=\"me-2 text-light\"><i class=\"fa-solid fa-tag\"></i></span> \r\n");
      out.write("                <span>Categories</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"mt-2\">\r\n");
      out.write("              <a href=\"#\" class=\"nav-link px-3 active\">\r\n");
      out.write("                <span class=\"me-2 text-light\"><i class=\"fa-solid fa-clipboard\"></i></span> \r\n");
      out.write("                <span>View Orders</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"mt-2\">\r\n");
      out.write("              <a href=\"#\" class=\"nav-link px-3 active\">\r\n");
      out.write("                <span class=\"me-2 text-light\"><i class=\"fa-solid fa-credit-card\"></i></span> \r\n");
      out.write("                <span>View Payments</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"mt-2\">\r\n");
      out.write("              <a href=\"#\" class=\"nav-link px-3 active\">\r\n");
      out.write("                <span class=\"me-2 text-light\"><i class=\"fa-solid fa-users\"></i></i></span> \r\n");
      out.write("                <span>Users</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("           \r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</aside>\r\n");
      out.write("  <!-- card -->\r\n");
      out.write("<main class=\"\" id=\"main-section\">\r\n");
      out.write("  <div class=\"container-fluid \" >\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"row my-2 gy-5 \">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-sm-12 col-md-4 col-lg-4  d-flex justify-content-center \"  >\r\n");
      out.write("        <div class=\"card align-self-center py-3 bg-primary \" style=\"width: 18rem; \"> \r\n");
      out.write("          <div class=\"card-body d-flex flex-column align-items-center  \">\r\n");
      out.write("            <span class=\"text-light\"><i class=\"fa-solid fa-users fa-3x\"></i></span>\r\n");
      out.write("             <p class=\"fs-5 text-light  mt-3 mb-0\">1234</p>\r\n");
      out.write("            <h5 class=\"card-title text-light fw-bold\">Users</h5>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-sm-12 col-md-4 col-lg-4  d-flex justify-content-center\">\r\n");
      out.write("        <div class=\"card  align-self-center py-3 bg-secondary \" style=\"width: 18rem;\">\r\n");
      out.write("          <div class=\"card-body d-flex flex-column align-items-center  \">\r\n");
      out.write("            <span class=\"text-light\"><i class=\"fa-solid fa-boxes-stacked fa-3x\"></i></span>\r\n");
      out.write("             <p class=\"fs-5 text-light mt-3 mb-0\">1234</p>\r\n");
      out.write("            <h5 class=\"card-title text-light fw-bold\">Products</h5>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-sm-12 col-md-4 col-lg-4  d-flex justify-content-center\">\r\n");
      out.write("        <div class=\"card  align-self-center py-3 bg-success \" style=\"width: 18rem;\">\r\n");
      out.write("          <div class=\"card-body d-flex flex-column align-items-center  \">\r\n");
      out.write("            <span class=\"text-light\"><i class=\"fa-solid fa-tag fa-3x\"></i></span>\r\n");
      out.write("             <p class=\"fs-5 text-light  mt-3 mb-0\">1234</p>\r\n");
      out.write("            <h5 class=\"card-title text-light fw-bold\">Categories</h5>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row my-2 gy-5 \">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-sm-12 col-md-4 col-lg-4  d-flex justify-content-center \" >\r\n");
      out.write("        <div class=\"card align-self-center py-3 bg-danger \" style=\"width: 18rem;\"> \r\n");
      out.write("          <div class=\"card-body d-flex flex-column align-items-center  \">\r\n");
      out.write("            <span class=\"text-light\"><i class=\"fa-solid fa-receipt fa-3x \"></i></span>\r\n");
      out.write("             <p class=\"fs-5 text-light  mt-3 mb-0\">123</p>\r\n");
      out.write("            <h5 class=\"card-title text-light fw-bold \">Orders</h5>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-sm-12 col-md-4 col-lg-4  d-flex justify-content-center\">\r\n");
      out.write("        <div class=\"card  align-self-center py-3 bg-warning  \" style=\"width: 18rem;\">\r\n");
      out.write("          <div class=\"card-body d-flex flex-column align-items-center  \">\r\n");
      out.write("            <span class=\"text-light\" ><i class=\"fa-solid fa-box fa-3x\"></i></span>\r\n");
      out.write("             <p class=\"fs-5 text-light  mt-3 mb-0 \"><i class=\"fa-solid fa-plus\"></i></p>\r\n");
      out.write("             <h5 class=\"card-title text-light fw-bold \"><a href=\"./addProduct.jsp\" class=\"nav-link active\">Product</a></h5>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-sm-12 col-md-4 col-lg-4  d-flex justify-content-center\">\r\n");
      out.write("        <div class=\"card  align-self-center py-3 bg-info \" style=\"width: 18rem;\">\r\n");
      out.write("          <div class=\"card-body d-flex flex-column align-items-center  \">\r\n");
      out.write("            <span class=\"text-light\"><i class=\"fa-solid fa-list fa-3x\"></i></span>\r\n");
      out.write("             <p class=\"fs-5 text-light  mt-3 mb-0\"><i class=\"fa-solid fa-plus\"></i></p>\r\n");
      out.write("             <h5 class=\"card-title text-light fw-bold \"><a href=\"./addCategory.jsp\" class=\"nav-link active\">Category</a></h5>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("   </div>\r\n");
      out.write("</main>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
