/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-09-27 17:52:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.demo.dao.wishlistDao;
import com.demo.product.Product;
import com.demo.product.ProductDao;
import com.demo.category.Category;
import com.demo.category.CategoryDao;
import com.demo.helper.Reduce;
import java.util.List;
import java.util.HashSet;
import java.util.Set;
import java.io.File;
import com.demo.User;
import com.demo.UserDao;
import com.demo.utility.Cart;
import com.demo.dao.CartDao;
import com.demo.order.MyOrder;
import com.demo.order.OrderDao;

public final class logout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/Users/rutvi/OneDrive/Desktop/fashion-app/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/my-fashion-app/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0%20(1).jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
    _jspx_dependants.put("/./components/header.jsp", Long.valueOf(1721322259342L));
    _jspx_dependants.put("/./components/footer.jsp", Long.valueOf(1720289183002L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0 (1).jar", Long.valueOf(1717239385690L));
    _jspx_dependants.put("/../components/common.jsp", Long.valueOf(1720372119264L));
    _jspx_dependants.put("/./components/../components/imports.jsp", Long.valueOf(1720165404251L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(16);
    _jspx_imports_classes.add("com.demo.product.Product");
    _jspx_imports_classes.add("com.demo.dao.CartDao");
    _jspx_imports_classes.add("com.demo.order.OrderDao");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("com.demo.category.Category");
    _jspx_imports_classes.add("java.io.File");
    _jspx_imports_classes.add("com.demo.helper.Reduce");
    _jspx_imports_classes.add("java.util.HashSet");
    _jspx_imports_classes.add("com.demo.User");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.demo.product.ProductDao");
    _jspx_imports_classes.add("com.demo.category.CategoryDao");
    _jspx_imports_classes.add("com.demo.UserDao");
    _jspx_imports_classes.add("com.demo.order.MyOrder");
    _jspx_imports_classes.add("com.demo.utility.Cart");
    _jspx_imports_classes.add("com.demo.dao.wishlistDao");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/other/stylesheet.css?modified=20012009\">\r\n");
      out.write("  <!-- Owl Carousel CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css\" integrity=\"sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css\" integrity=\"sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("   <!-- Bootstrap Icons CSS -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css\" rel=\"stylesheet\">\r\n");
      out.write(" \r\n");
      out.write("  <!-- jQuery -->\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js\" integrity=\"sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("  <!-- Owl Carousel JS -->\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js\" integrity=\"sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("  \r\n");
      out.write("<!--bootstrap  -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.6/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/c13edee66d.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Wittgenstein:ital,wght@0,400..900;1,400..900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/img.png\" />\r\n");
      out.write("<title>Logout</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

      User currentUser = (User)session.getAttribute("current-user");

      int totalWishlist = 0;
      int totalCartItems = 0;
      
      if(currentUser != null){
    	  int userid = currentUser.getUserId();
    	  totalWishlist = wishlistDao.getTotalWhistlistProducts(userid);
    	  totalCartItems = CartDao.getTotalCartProducts(userid);
      }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <!-- first navbar  -->\r\n");
      out.write("  <div class=\"position-fixed z-3 mt-0 w-100 top-0\" id=\"header-container\">\r\n");
      out.write("        <div class=\"container-fluid bg-black text-white text-center p-1 mb-0\">\r\n");
      out.write("           <span id=\"first-nav\">Spring-Summer'24 SALE! Flat40%  OFF*</span>\r\n");
      out.write("		 </div> \r\n");
      out.write("		     <!--second navbar  -->\r\n");
      out.write("		     <nav class=\"navbar navbar-expand-lg  border-bottom border-light-subtle \" id=\"second-navbar\">\r\n");
      out.write("		        <div class=\"container-fluid d-flex justify-content-between row  \">\r\n");
      out.write("		          <div class=\"col-lg-4 col-sm-4 col-xs-4 align-self-start align align-self-center\">\r\n");
      out.write("		             <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#thirdNavbar\" aria-controls=\"thirdNavbarLabel\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("			            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			         </button>\r\n");
      out.write("		          </div>\r\n");
      out.write("		           <div class=\"col-lg-4 col-sm-4 col-xs-4 align-self-center\" >\r\n");
      out.write("		            <a class=\"navbar-brand \" href=\"#\">\r\n");
      out.write("		                <!-- add image -->\r\n");
      out.write("		                ");
      out.write("\r\n");
      out.write("		                <span id=\"brand-name\">FASHION</span>\r\n");
      out.write("		            </a>\r\n");
      out.write("		           </div>\r\n");
      out.write("		           <div class=\"d-flex justify-content-center align-items-center col-lg-4 col-sm-4 col-4 align-self-center  \" style=\"height:3.4rem\" >\r\n");
      out.write("		              <div class=\"col-lg-8 d-none d-lg-block  \" style=\"height:100%\"  >\r\n");
      out.write("				        <div class=\" w-100 \" style=\"height:100%\">\r\n");
      out.write("				           <form class=\"d-flex w-100 align-items-center\" style=\"height:100%\" role=\"search\" id=\"nav-2-form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp\">\r\n");
      out.write("							   <div class=\"input-group \">\r\n");
      out.write("								    <input class=\"form-control\" name=\"searchItem\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("								    <button class=\"btn btn-outline-secondary border \" type=\"submit\" aria-label=\"Search\" id=\"searched-btn\">\r\n");
      out.write("								      <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18\" height=\"18\" fill=\"currentColor\" class=\"bi bi-search\" viewBox=\"0 0 16 16\">\r\n");
      out.write("								        <path d=\"M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0\"/>\r\n");
      out.write("								      </svg>\r\n");
      out.write("								    </button>\r\n");
      out.write("								  </div>\r\n");
      out.write("						  </form>	\r\n");
      out.write("				        </div> \r\n");
      out.write("		              </div>\r\n");
      out.write("		              <div class=\"col-lg-4 col-sm-12 justify-content-evenly d-flex align-items-center \" id=\"header-section\">\r\n");
      out.write("		                 <div class=\"row row-col-4\">\r\n");
      out.write("		                     <div class=\"col d-flex align-items-center\">\r\n");
      out.write("		                        <div class=\"dropdown\" id=\"header-dropdown\">\r\n");
      out.write("		                              <span class=\"fs-3\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" ><i class=\"bi bi-person \"></i></span>\r\n");
      out.write("					                  \r\n");
      out.write("					                   <ul class=\"dropdown-menu\" id=\"header-dropdown-menu\">\r\n");
      out.write("					                        ");
 
									            Boolean isLoggedIn = (Boolean) session.getAttribute("isLoggedIn");
					                            System.out.print(isLoggedIn);
									            if (isLoggedIn != null && isLoggedIn) {
									        
      out.write("\r\n");
      out.write("									            <li><a class=\"dropdown-item\" href=\"profile.jsp\">My Account</a></li>\r\n");
      out.write("									            \r\n");
      out.write("									            <li>\r\n");
      out.write("										            <form action=\"logoutServlet\" method=\"post\">\r\n");
      out.write("										             <button class=\"dropdown-item\" type=\"submit\">Logout</button>\r\n");
      out.write("										            </form>\r\n");
      out.write("									            </li>\r\n");
      out.write("									        ");
 
									            } else {
									        
      out.write("\r\n");
      out.write("									            <li><a class=\"dropdown-item\" href=\"registor.jsp\">Register</a></li>\r\n");
      out.write("									            <li><a class=\"dropdown-item\" href=\"login.jsp\">Login</a></li>\r\n");
      out.write("									        ");
 
									            } 
									        
      out.write("\r\n");
      out.write("									   </ul>\r\n");
      out.write("				                 </div>\r\n");
      out.write("				                     \r\n");
      out.write("		                     </div>\r\n");
      out.write("		                     <div class=\"col d-flex align-items-center\">\r\n");
      out.write("				                          <!-- add option -->\r\n");
      out.write("				                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/wishlist.jsp\" class=\"position-relative\">\r\n");
      out.write("				                 <span class=\" fs-4\">\r\n");
      out.write("				                     <i class=\"bi bi-heart\"></i>\r\n");
      out.write("				                     <span class=\"position-absolute top-0 start-100 translate-middle px-2 text-light badge  rounded-circle\">\r\n");
      out.write("									    <span style=\"font-size:0.88rem\">");
      out.print( totalWishlist);
      out.write("</span>\r\n");
      out.write("									 </span>\r\n");
      out.write("				                 </span>\r\n");
      out.write("				                   \r\n");
      out.write("				                </a>\r\n");
      out.write("		                     </div>\r\n");
      out.write("		                     <div class=\"col d-flex align-items-center\">\r\n");
      out.write("				                        <!-- add heart -->\r\n");
      out.write("				                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/addtocart.jsp\" class=\"position-relative\"> \r\n");
      out.write("				                   <span class=\" fs-4\">\r\n");
      out.write("				                     <i class=\"bi bi-bag custom-icon\"></i>\r\n");
      out.write("				                      <span class=\"position-absolute top-0 start-100 translate-middle px-2 text-light badge rounded-circle\">\r\n");
      out.write("									    <span style=\"font-size:0.85rem\">");
      out.print(totalCartItems );
      out.write("</span>\r\n");
      out.write("									 </span>\r\n");
      out.write("				                   </span>\r\n");
      out.write("				                </a>\r\n");
      out.write("				               <!-- add bag -->\r\n");
      out.write("		                     \r\n");
      out.write("		                     </div>\r\n");
      out.write("		                 </div>\r\n");
      out.write("		               \r\n");
      out.write("		               \r\n");
      out.write("		              </div>\r\n");
      out.write("		              \r\n");
      out.write("		           </div>\r\n");
      out.write("		        </div>\r\n");
      out.write("        \r\n");
      out.write("		      </nav>\r\n");
      out.write("		   <!--third navbar  -->\r\n");
      out.write("		   <nav class=\"navbar  navbar-expand-lg border-bottom border-light-subtle  \" id=\"third-navbar-container\">\r\n");
      out.write("		        <div class=\"container-fluid\">\r\n");
      out.write("		         \r\n");
      out.write("		          <div class=\"offcanvas offcanvas-start\" tabindex=\"-1\" id=\"thirdNavbar\" aria-labelledby=\"thirdNavbarLabel\">\r\n");
      out.write("		                <div class=\"offcanvas-header\">\r\n");
      out.write("		                \r\n");
      out.write("		                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\r\n");
      out.write("		                </div>\r\n");
      out.write("		              <div class=\"offcanvas-body\">\r\n");
      out.write("		               <div class=\"container d-lg-block d-none\">\r\n");
      out.write("		                <ul class=\"navbar-nav justify-content-end flex-grow-1 pe-3 \">\r\n");
      out.write("		                 <div class=\"d-flex justify-content-evenly  w-100\">\r\n");
      out.write("		                    <div class=\"p-2\">\r\n");
      out.write("		                      <nav class=\"nav-item\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" class=\"nav-link\">Home</a></nav>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                    <div class=\"p-2\">\r\n");
      out.write("		                      <nav class=\"nav-item\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=all\" class=\"nav-link\">All products</a></nav>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                    <div class=\"p-2\">\r\n");
      out.write("		                     <div class=\" nav-item dropdown\">\r\n");
      out.write("		                        <a class=\"nav-link \" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("		                          Tops <span class=\"ps-2 small\"><i class=\"fa-solid fa-chevron-down\"></i></span>\r\n");
      out.write("		                        </a>\r\n");
      out.write("		                        <ul class=\"dropdown-menu\">\r\n");
      out.write("		                          <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Tops\">Floweral Tops</a></li>\r\n");
      out.write("		                          <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Tops\">Cropped Tops</a></li>\r\n");
      out.write("		                          <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Tops\">Tops</a></li>\r\n");
      out.write("		                        </ul>\r\n");
      out.write("		                     </div>\r\n");
      out.write("		                     \r\n");
      out.write("		                    </div>\r\n");
      out.write("		                  \r\n");
      out.write("		                    <div class=\"p-2\">\r\n");
      out.write("		                      <li class=\"nav-item\">\r\n");
      out.write("		                      <a class=\"nav-link link \" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Co-ords\" role=\"button\"  >\r\n");
      out.write("		                        Co-ords\r\n");
      out.write("		                      </a></li>\r\n");
      out.write("		                      \r\n");
      out.write("		                    </div>\r\n");
      out.write("		                    <div class=\"p-2\">\r\n");
      out.write("		                      <div class=\"nav-item dropdown\">\r\n");
      out.write("		\r\n");
      out.write("		                      <a class=\"nav-link \" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("		                        Exclusive  <span class=\"ps-2 small\"><i class=\"fa-solid fa-chevron-down\"></i></span>\r\n");
      out.write("		                      </a>\r\n");
      out.write("		                      <ul class=\"dropdown-menu\">\r\n");
      out.write("		                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Tops\">Tops</a></li>\r\n");
      out.write("		                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Skirts and Shorts\">Shorts</a></li>\r\n");
      out.write("		                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Dresses\">Dresses</a></li>\r\n");
      out.write("		                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Denim\">Denim</a></li>\r\n");
      out.write("		                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Co-ords\">Jumpsuit</a></li>\r\n");
      out.write("		                      </ul>\r\n");
      out.write("		                      </div>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                    <div class=\"p-2\">\r\n");
      out.write("		                      <div class=\"nav-item dropdown\">\r\n");
      out.write("		                      <a class=\"nav-link \" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("		                        New In <span class=\"ps-2 small\"><i class=\"fa-solid fa-chevron-down\"></i></span>\r\n");
      out.write("		                      </a>\r\n");
      out.write("		                      <ul class=\"dropdown-menu\">\r\n");
      out.write("		                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Tops\">Tops</a></li>\r\n");
      out.write("		                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Skirts and Shorts\">Shorts</a></li>\r\n");
      out.write("		                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Denim\">Denim</a></li>\r\n");
      out.write("		                      </ul>\r\n");
      out.write("		                      </div>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                 </div>\r\n");
      out.write("		                    \r\n");
      out.write("		                </ul>\r\n");
      out.write("		               </div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("              <!-- navbar for small screen -->\r\n");
      out.write("              <div class=\"container d-block d-lg-none mb-5  \">\r\n");
      out.write("                <div class=\"\">\r\n");
      out.write("                  <ul class=\"navbar-nav justify-content-end flex-grow-1 pe-3\">\r\n");
      out.write("                    <div class=\"p-2\">\r\n");
      out.write("                      <nav class=\"nav-item\"><a href=\"#\" class=\"nav-link\">Home</a></nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"p-2\">\r\n");
      out.write("                      <nav class=\"nav-item\"><a href=\"#\" class=\"nav-link\">All products</a></nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"p-2\">\r\n");
      out.write("                      <div class=\" \">\r\n");
      out.write("                        <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#collapseHome3\" role=\"button\" aria-expanded=\"false\" aria-controls=\"collapseHome\">\r\n");
      out.write("                        Tops <span class=\"ps-2 small\"><i class=\"fa-solid fa-chevron-down\"></i></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"collapse\" id=\"collapseHome3\">\r\n");
      out.write("                          <div class=\"card card-body\">\r\n");
      out.write("                            <ul class=\"list-unstyled\">\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Floweral Tops</a></li>\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Cropped Tops</a></li>\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Tops</a></li>\r\n");
      out.write("                             </ul>\r\n");
      out.write("                           </div>\r\n");
      out.write("                         </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                   \r\n");
      out.write("                    <div class=\"p-2\">\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                      <a class=\"nav-link \" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                      Co-ords\r\n");
      out.write("                      </a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   \r\n");
      out.write("                    <div class=\"p-2\">\r\n");
      out.write("                      <div class=\"\">\r\n");
      out.write("                        <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#collapseHome2\" role=\"button\" aria-expanded=\"false\" aria-controls=\"collapseHome\">\r\n");
      out.write("                        Exclusive <span class=\"ps-2 small\"><i class=\"fa-solid fa-chevron-down\"></i></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"collapse\" id=\"collapseHome2\">\r\n");
      out.write("                          <div class=\"card card-body\">\r\n");
      out.write("                            <ul class=\"list-unstyled\">\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Tops</a></li>\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Shorts</a></li>\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Dresses</a></li>\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Denimes</a></li>\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Jumpsuit</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>  \r\n");
      out.write("                    <div class=\"p-2\">\r\n");
      out.write("                      <div class=\"\">\r\n");
      out.write("                       \r\n");
      out.write("                        <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#collapseHome1\" role=\"button\" aria-expanded=\"false\" aria-controls=\"collapseHome\">\r\n");
      out.write("                          New In <span class=\"ps-2 small\"><i class=\"fa-solid fa-chevron-down\"></i></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"collapse\" id=\"collapseHome1\">\r\n");
      out.write("                          <div class=\"card card-body\">\r\n");
      out.write("                            <ul class=\"list-unstyled\">\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Tops</a></li>\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Shorts</a></li>\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Denimes</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>  \r\n");
      out.write("                      \r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("             \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("		   \r\n");
      out.write("		   \r\n");
      out.write("		  \r\n");
      out.write("  </div>\r\n");
      out.write(" </header>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("   <div class=\"container-fluid ps-3 \" id=\"container\">\r\n");
      out.write("        <div class=\"logout-1\">\r\n");
      out.write("          <ul class=\"d-flex list-unstyled\">\r\n");
      out.write("	           <li class=\"p-1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\"><i class=\"fa-solid fa-house\"></i></a></li>\r\n");
      out.write("	           <li class=\"p-1\"><span>> </span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/profile.jsp\">ACCOUNT</a></li>\r\n");
      out.write("	           <li class=\"p-1\"><span>> </span><a href=\"index.jsp\">LOGOUT</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <h2 >Account Logout</h2>\r\n");
      out.write("        <div class=\" logout-para\"><p>You have been logged off your account. It is now safe to leave the computer.</p></div>\r\n");
      out.write("        <div class=\" logout-para\"><p>Your shopping cart has been saved, the items inside it will be restored whenever you log back into your account.</p></div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"index.jsp\" class=\"btn btn-success p-2 ps-3 pe-3 ms-4\" role=\"button\" >Continue</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<footer class=\"footer pt-lg-5 pt-4 position-sticky bootom-0\">\r\n");
      out.write("  <div class=\" bg-light\" id=\"footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("       <div class=\"row py-4\">\r\n");
      out.write("       <div class=\"col-lg-4 col-md-12 col-12 mb-sm-4 \">\r\n");
      out.write("         <h6 class=\"mb-2 px-3\">Categories</h6>\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("           <div class=\"col-6 \">\r\n");
      out.write("             <ul class=\"nav flex-column\">\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Athleisure </a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Skirts </a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Skorts</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Crop Tops </a></li>\r\n");
      out.write("             </ul>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"col-6\">\r\n");
      out.write("                <!-- list -->\r\n");
      out.write("              <ul class=\"nav flex-column\">\r\n");
      out.write("                <li class=\"nav-item mb-0 \"><a href=\"#!\" class=\"nav-link\">Dresses</a></li>\r\n");
      out.write("                <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Tops </a></li>\r\n");
      out.write("                <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Shirts  </a></li>\r\n");
      out.write("                <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Jackets</a></li>\r\n");
      out.write("                <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Bottomwear </a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("               \r\n");
      out.write("           </div>\r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"col-12 col-lg-8 col-md-12\">\r\n");
      out.write("         <div class=\"row \">\r\n");
      out.write("           <div class=\"col-12 col-sm-12 col-md-3 pb-2 pb-md-0\">\r\n");
      out.write("             <h6 class=\"mb-2 px-3\">Shop By Colors</h6>\r\n");
      out.write("             <ul class=\"nav flex-column \">\r\n");
      out.write("               <li class=\"nav-item mb-0 \"><a href=\"#!\" class=\"nav-link\">Pink Dresses</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0 \"><a href=\"#!\" class=\"nav-link\">Red Tops</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#1\" class=\"nav-link\">Blog</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Blue Tops</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Yellow Tops</a></li>\r\n");
      out.write("             </ul>\r\n");
      out.write("           </div> \r\n");
      out.write("           <div class=\"col-6 col-sm-6 col-md-3 pb-2 pb-md-0\">\r\n");
      out.write("             <h6 class=\"mb-2 px-3\">For Consumers</h6>\r\n");
      out.write("             <ul class=\"nav flex-column\">\r\n");
      out.write("                   <!-- list -->\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Payments</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Shipping</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Product Returns</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">FAQ</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"./pages/shop-checkout.html\" class=\"nav-link\">Shop Checkout</a></li>\r\n");
      out.write("             </ul>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"col-6 col-sm-6 col-md-3 pb-2 pb-md-0\">\r\n");
      out.write("             <h6 class=\"mb-2 px-3\">Contact Us</h6>    \r\n");
      out.write("             <ul class=\"nav flex-column\">\r\n");
      out.write("                 <!-- list -->\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Find a Store </a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Size Guide</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Track Order</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">FAQ</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">E-GIFT VOUCHER</a></li>\r\n");
      out.write("             </ul>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"col-6 col-sm-6 col-md-3 pb-2 pb-md-0\">\r\n");
      out.write("             <h6 class=\"mb-2 px-3\">Corporate Info</h6>   \r\n");
      out.write("             <ul class=\"nav flex-column\">\r\n");
      out.write("                 <!-- list -->\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">About Us</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">About Bestseller</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Promos &amp; Coupons</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Privacy policy</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">T&C</a></li>\r\n");
      out.write("             </ul>\r\n");
      out.write("           </div>\r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"border-top py-4\">\r\n");
      out.write("       <div class=\"row\">\r\n");
      out.write("         <div class=\"col-lg-5\">\r\n");
      out.write("           <ul>\r\n");
      out.write("             <li class=\"list-inline-item text-dark\">Payment Partners</li>\r\n");
      out.write("             <li class=\"list-inline-item\"><a href=\"!#\"><img src=\"images/footer/amazonpay.svg\" alt=\"amazon logo\"></a>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"list-inline-item\">\r\n");
      out.write("               <a href=\"!#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/footer/american-express.svg\" alt=\"\"></a>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"list-inline-item\">\r\n");
      out.write("               <a href=\"#!\"><img src=\"images/footer/paypal.svg\" alt=\"\"></a>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"list-inline-item\">\r\n");
      out.write("               <a href=\"#!\"><img src=\"images/footer/mastercard.svg\" alt=\"\"></a>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"list-inline-item\">\r\n");
      out.write("               <a href=\"#!\"><img src=\"images/footer/visa.svg\" alt=\"\"></a>\r\n");
      out.write("             </li>\r\n");
      out.write("           </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"col-lg-7 \">\r\n");
      out.write("            <ul class=\"list-inline mb-0 text-lg-end text-center\">\r\n");
      out.write("             <li class=\"list-inline-item mb-0  text-dark\">Get deliveries with FreshCart</li>\r\n");
      out.write("             <li class=\"list-inline-item ms-4\">\r\n");
      out.write("               <a href=\"#!\"> <img src=\"images/footer/appstore-btn.svg\" alt=\"\" style=\"width: 140px;\"></a></li>\r\n");
      out.write("             <li class=\"list-inline-item\">\r\n");
      out.write("               <a href=\"#!\"> <img src=\"images/footer/googleplay-btn.svg\" alt=\"\" style=\"width: 140px;\"></a></li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"border-top py-4\">\r\n");
      out.write("       <div class=\"d-flex justify-content-center \" id=\"social_media\">\r\n");
      out.write("         <div class=\"text-muted\"><small><p class=\"px-2 d-inline\">Follow us on</p>\r\n");
      out.write("          <li class=\"list-inline-item px-0\">\r\n");
      out.write("            <a href=\"!#\" class=\"fs-4 \">\r\n");
      out.write("              <i class=\"fa-brands fa-facebook\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("         <li class=\"list-inline-item\">\r\n");
      out.write("            <a href=\"!#\" class=\"fs-4 \">\r\n");
      out.write("              <i class=\"fa-brands fa-instagram\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("         <li class=\"list-inline-item\">\r\n");
      out.write("            <a href=\"!#\" class=\"fs-4 \">\r\n");
      out.write("              <i class=\"fa-brands fa-x-twitter\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("         </small> \r\n");
      out.write(" \r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
