/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-07-18 17:04:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.HashSet;
import com.demo.product.Product;
import com.demo.product.ProductDao;
import com.demo.category.Category;
import com.demo.category.CategoryDao;
import com.demo.helper.Reduce;
import java.util.List;
import java.util.HashSet;
import java.util.Set;
import java.io.File;
import com.demo.User;
import com.demo.UserDao;
import com.demo.utility.Cart;
import com.demo.dao.CartDao;
import com.demo.order.MyOrder;
import com.demo.order.OrderDao;
import com.demo.dao.wishlistDao;
import com.demo.product.Product;
import com.demo.product.ProductDao;
import com.demo.category.Category;
import com.demo.category.CategoryDao;
import com.demo.helper.Reduce;
import java.util.List;
import java.util.HashSet;
import java.util.Set;
import java.io.File;
import com.demo.User;
import com.demo.UserDao;
import com.demo.utility.Cart;
import com.demo.dao.CartDao;
import com.demo.order.MyOrder;
import com.demo.order.OrderDao;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/C:/Users/rutvi/OneDrive/Desktop/fashion-app/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/my-fashion-app/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0%20(1).jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
    _jspx_dependants.put("/./components/header.jsp", Long.valueOf(1721322259342L));
    _jspx_dependants.put("/../components/imports.jsp", Long.valueOf(1720165404251L));
    _jspx_dependants.put("/./components/footer.jsp", Long.valueOf(1720289183002L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0 (1).jar", Long.valueOf(1717239385690L));
    _jspx_dependants.put("/../components/common.jsp", Long.valueOf(1720372119264L));
    _jspx_dependants.put("/./components/../components/imports.jsp", Long.valueOf(1720165404251L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(16);
    _jspx_imports_classes.add("com.demo.product.Product");
    _jspx_imports_classes.add("com.demo.dao.CartDao");
    _jspx_imports_classes.add("com.demo.order.OrderDao");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("com.demo.category.Category");
    _jspx_imports_classes.add("java.io.File");
    _jspx_imports_classes.add("com.demo.helper.Reduce");
    _jspx_imports_classes.add("java.util.HashSet");
    _jspx_imports_classes.add("com.demo.User");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.demo.product.ProductDao");
    _jspx_imports_classes.add("com.demo.category.CategoryDao");
    _jspx_imports_classes.add("com.demo.UserDao");
    _jspx_imports_classes.add("com.demo.order.MyOrder");
    _jspx_imports_classes.add("com.demo.utility.Cart");
    _jspx_imports_classes.add("com.demo.dao.wishlistDao");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/other/stylesheet.css?modified=20012009\">\r\n");
      out.write("  <!-- Owl Carousel CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css\" integrity=\"sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css\" integrity=\"sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("   <!-- Bootstrap Icons CSS -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css\" rel=\"stylesheet\">\r\n");
      out.write(" \r\n");
      out.write("  <!-- jQuery -->\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js\" integrity=\"sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("  <!-- Owl Carousel JS -->\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js\" integrity=\"sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("  \r\n");
      out.write("<!--bootstrap  -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.6/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/c13edee66d.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Wittgenstein:ital,wght@0,400..900;1,400..900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/other/product.css\">\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write(" <link rel=\"icon\" type=\"image/png\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/img.png\" />\r\n");
      out.write("<title>Products</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");

            User user = (User)session.getAttribute("current-user");
            List <Product> list =null;
            
             String category = request.getParameter("category");
             System.out.println("category : "+category);
             String searchedQuery = request.getParameter("searchItem");
             System.out.println("searched query  request : "+searchedQuery);
          	if (category == null ) {
		   		if(searchedQuery != null){
		   			System.out.println("In searched query ");
			   		list = ProductDao.getSearchedProduct(searchedQuery);
			   		System.out.println("In searched query 2nd ");
		   		}
		   	} else         	
			   if (category != null && category.equals("all")) {
			   		
			   		list = ProductDao.getAllProducts();
			
			   	} else if(category != null) {
			   		list = ProductDao.getPerticulerProducts(category);
			   	}
			   	
		
			   	request.setAttribute("list", list);
				   System.out.println("list : "+list);
			   	List<Category> catList = CategoryDao.getCategories();
			   	request.setAttribute("catList", catList);
			
			   	HashSet<String> colors = ProductDao.getColors();
			   	request.setAttribute("colors", colors);
			   	
			   	
			   	
			   	/* 
			   	  
			   	
			   	*/
   
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("   <div class=\"mb-5 pb-4\">\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

      User currentUser = (User)session.getAttribute("current-user");

      int totalWishlist = 0;
      int totalCartItems = 0;
      
      if(currentUser != null){
    	  int userid = currentUser.getUserId();
    	  totalWishlist = wishlistDao.getTotalWhistlistProducts(userid);
    	  totalCartItems = CartDao.getTotalCartProducts(userid);
      }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <!-- first navbar  -->\r\n");
      out.write("  <div class=\"position-fixed z-3 mt-0 w-100 top-0\" id=\"header-container\">\r\n");
      out.write("        <div class=\"container-fluid bg-black text-white text-center p-1 mb-0\">\r\n");
      out.write("           <span id=\"first-nav\">Spring-Summer'24 SALE! Flat40%  OFF*</span>\r\n");
      out.write("		 </div> \r\n");
      out.write("		     <!--second navbar  -->\r\n");
      out.write("		     <nav class=\"navbar navbar-expand-lg  border-bottom border-light-subtle \" id=\"second-navbar\">\r\n");
      out.write("		        <div class=\"container-fluid d-flex justify-content-between row  \">\r\n");
      out.write("		          <div class=\"col-lg-4 col-sm-4 col-xs-4 align-self-start align align-self-center\">\r\n");
      out.write("		             <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#thirdNavbar\" aria-controls=\"thirdNavbarLabel\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("			            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			         </button>\r\n");
      out.write("		          </div>\r\n");
      out.write("		           <div class=\"col-lg-4 col-sm-4 col-xs-4 align-self-center\" >\r\n");
      out.write("		            <a class=\"navbar-brand \" href=\"#\">\r\n");
      out.write("		                <!-- add image -->\r\n");
      out.write("		                ");
      out.write("\r\n");
      out.write("		                <span id=\"brand-name\">FASHION</span>\r\n");
      out.write("		            </a>\r\n");
      out.write("		           </div>\r\n");
      out.write("		           <div class=\"d-flex justify-content-center align-items-center col-lg-4 col-sm-4 col-4 align-self-center  \" style=\"height:3.4rem\" >\r\n");
      out.write("		              <div class=\"col-lg-8 d-none d-lg-block  \" style=\"height:100%\"  >\r\n");
      out.write("				        <div class=\" w-100 \" style=\"height:100%\">\r\n");
      out.write("				           <form class=\"d-flex w-100 align-items-center\" style=\"height:100%\" role=\"search\" id=\"nav-2-form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp\">\r\n");
      out.write("							   <div class=\"input-group \">\r\n");
      out.write("								    <input class=\"form-control\" name=\"searchItem\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("								    <button class=\"btn btn-outline-secondary border \" type=\"submit\" aria-label=\"Search\" id=\"searched-btn\">\r\n");
      out.write("								      <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18\" height=\"18\" fill=\"currentColor\" class=\"bi bi-search\" viewBox=\"0 0 16 16\">\r\n");
      out.write("								        <path d=\"M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0\"/>\r\n");
      out.write("								      </svg>\r\n");
      out.write("								    </button>\r\n");
      out.write("								  </div>\r\n");
      out.write("						  </form>	\r\n");
      out.write("				        </div> \r\n");
      out.write("		              </div>\r\n");
      out.write("		              <div class=\"col-lg-4 col-sm-12 justify-content-evenly d-flex align-items-center \" id=\"header-section\">\r\n");
      out.write("		                 <div class=\"row row-col-4\">\r\n");
      out.write("		                     <div class=\"col d-flex align-items-center\">\r\n");
      out.write("		                        <div class=\"dropdown\" id=\"header-dropdown\">\r\n");
      out.write("		                              <span class=\"fs-3\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" ><i class=\"bi bi-person \"></i></span>\r\n");
      out.write("					                  \r\n");
      out.write("					                   <ul class=\"dropdown-menu\" id=\"header-dropdown-menu\">\r\n");
      out.write("					                        ");
 
									            Boolean isLoggedIn = (Boolean) session.getAttribute("isLoggedIn");
					                            System.out.print(isLoggedIn);
									            if (isLoggedIn != null && isLoggedIn) {
									        
      out.write("\r\n");
      out.write("									            <li><a class=\"dropdown-item\" href=\"profile.jsp\">My Account</a></li>\r\n");
      out.write("									            \r\n");
      out.write("									            <li>\r\n");
      out.write("										            <form action=\"logoutServlet\" method=\"post\">\r\n");
      out.write("										             <button class=\"dropdown-item\" type=\"submit\">Logout</button>\r\n");
      out.write("										            </form>\r\n");
      out.write("									            </li>\r\n");
      out.write("									        ");
 
									            } else {
									        
      out.write("\r\n");
      out.write("									            <li><a class=\"dropdown-item\" href=\"registor.jsp\">Register</a></li>\r\n");
      out.write("									            <li><a class=\"dropdown-item\" href=\"login.jsp\">Login</a></li>\r\n");
      out.write("									        ");
 
									            } 
									        
      out.write("\r\n");
      out.write("									   </ul>\r\n");
      out.write("				                 </div>\r\n");
      out.write("				                     \r\n");
      out.write("		                     </div>\r\n");
      out.write("		                     <div class=\"col d-flex align-items-center\">\r\n");
      out.write("				                          <!-- add option -->\r\n");
      out.write("				                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/wishlist.jsp\" class=\"position-relative\">\r\n");
      out.write("				                 <span class=\" fs-4\">\r\n");
      out.write("				                     <i class=\"bi bi-heart\"></i>\r\n");
      out.write("				                     <span class=\"position-absolute top-0 start-100 translate-middle px-2 text-light badge  rounded-circle\">\r\n");
      out.write("									    <span style=\"font-size:0.88rem\">");
      out.print( totalWishlist);
      out.write("</span>\r\n");
      out.write("									 </span>\r\n");
      out.write("				                 </span>\r\n");
      out.write("				                   \r\n");
      out.write("				                </a>\r\n");
      out.write("		                     </div>\r\n");
      out.write("		                     <div class=\"col d-flex align-items-center\">\r\n");
      out.write("				                        <!-- add heart -->\r\n");
      out.write("				                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/addtocart.jsp\" class=\"position-relative\"> \r\n");
      out.write("				                   <span class=\" fs-4\">\r\n");
      out.write("				                     <i class=\"bi bi-bag custom-icon\"></i>\r\n");
      out.write("				                      <span class=\"position-absolute top-0 start-100 translate-middle px-2 text-light badge rounded-circle\">\r\n");
      out.write("									    <span style=\"font-size:0.85rem\">");
      out.print(totalCartItems );
      out.write("</span>\r\n");
      out.write("									 </span>\r\n");
      out.write("				                   </span>\r\n");
      out.write("				                </a>\r\n");
      out.write("				               <!-- add bag -->\r\n");
      out.write("		                     \r\n");
      out.write("		                     </div>\r\n");
      out.write("		                 </div>\r\n");
      out.write("		               \r\n");
      out.write("		               \r\n");
      out.write("		              </div>\r\n");
      out.write("		              \r\n");
      out.write("		           </div>\r\n");
      out.write("		        </div>\r\n");
      out.write("        \r\n");
      out.write("		      </nav>\r\n");
      out.write("		   <!--third navbar  -->\r\n");
      out.write("		   <nav class=\"navbar  navbar-expand-lg border-bottom border-light-subtle  \" id=\"third-navbar-container\">\r\n");
      out.write("		        <div class=\"container-fluid\">\r\n");
      out.write("		         \r\n");
      out.write("		          <div class=\"offcanvas offcanvas-start\" tabindex=\"-1\" id=\"thirdNavbar\" aria-labelledby=\"thirdNavbarLabel\">\r\n");
      out.write("		                <div class=\"offcanvas-header\">\r\n");
      out.write("		                \r\n");
      out.write("		                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\r\n");
      out.write("		                </div>\r\n");
      out.write("		              <div class=\"offcanvas-body\">\r\n");
      out.write("		               <div class=\"container d-lg-block d-none\">\r\n");
      out.write("		                <ul class=\"navbar-nav justify-content-end flex-grow-1 pe-3 \">\r\n");
      out.write("		                 <div class=\"d-flex justify-content-evenly  w-100\">\r\n");
      out.write("		                    <div class=\"p-2\">\r\n");
      out.write("		                      <nav class=\"nav-item\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" class=\"nav-link\">Home</a></nav>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                    <div class=\"p-2\">\r\n");
      out.write("		                      <nav class=\"nav-item\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=all\" class=\"nav-link\">All products</a></nav>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                    <div class=\"p-2\">\r\n");
      out.write("		                     <div class=\" nav-item dropdown\">\r\n");
      out.write("		                        <a class=\"nav-link \" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("		                          Tops <span class=\"ps-2 small\"><i class=\"fa-solid fa-chevron-down\"></i></span>\r\n");
      out.write("		                        </a>\r\n");
      out.write("		                        <ul class=\"dropdown-menu\">\r\n");
      out.write("		                          <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Tops\">Floweral Tops</a></li>\r\n");
      out.write("		                          <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Tops\">Cropped Tops</a></li>\r\n");
      out.write("		                          <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Tops\">Tops</a></li>\r\n");
      out.write("		                        </ul>\r\n");
      out.write("		                     </div>\r\n");
      out.write("		                     \r\n");
      out.write("		                    </div>\r\n");
      out.write("		                  \r\n");
      out.write("		                    <div class=\"p-2\">\r\n");
      out.write("		                      <li class=\"nav-item\">\r\n");
      out.write("		                      <a class=\"nav-link link \" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Co-ords\" role=\"button\"  >\r\n");
      out.write("		                        Co-ords\r\n");
      out.write("		                      </a></li>\r\n");
      out.write("		                      \r\n");
      out.write("		                    </div>\r\n");
      out.write("		                    <div class=\"p-2\">\r\n");
      out.write("		                      <div class=\"nav-item dropdown\">\r\n");
      out.write("		\r\n");
      out.write("		                      <a class=\"nav-link \" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("		                        Exclusive  <span class=\"ps-2 small\"><i class=\"fa-solid fa-chevron-down\"></i></span>\r\n");
      out.write("		                      </a>\r\n");
      out.write("		                      <ul class=\"dropdown-menu\">\r\n");
      out.write("		                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Tops\">Tops</a></li>\r\n");
      out.write("		                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Skirts and Shorts\">Shorts</a></li>\r\n");
      out.write("		                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Dresses\">Dresses</a></li>\r\n");
      out.write("		                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Denim\">Denim</a></li>\r\n");
      out.write("		                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Co-ords\">Jumpsuit</a></li>\r\n");
      out.write("		                      </ul>\r\n");
      out.write("		                      </div>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                    <div class=\"p-2\">\r\n");
      out.write("		                      <div class=\"nav-item dropdown\">\r\n");
      out.write("		                      <a class=\"nav-link \" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("		                        New In <span class=\"ps-2 small\"><i class=\"fa-solid fa-chevron-down\"></i></span>\r\n");
      out.write("		                      </a>\r\n");
      out.write("		                      <ul class=\"dropdown-menu\">\r\n");
      out.write("		                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Tops\">Tops</a></li>\r\n");
      out.write("		                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Skirts and Shorts\">Shorts</a></li>\r\n");
      out.write("		                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product.jsp?category=Denim\">Denim</a></li>\r\n");
      out.write("		                      </ul>\r\n");
      out.write("		                      </div>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                 </div>\r\n");
      out.write("		                    \r\n");
      out.write("		                </ul>\r\n");
      out.write("		               </div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("              <!-- navbar for small screen -->\r\n");
      out.write("              <div class=\"container d-block d-lg-none mb-5  \">\r\n");
      out.write("                <div class=\"\">\r\n");
      out.write("                  <ul class=\"navbar-nav justify-content-end flex-grow-1 pe-3\">\r\n");
      out.write("                    <div class=\"p-2\">\r\n");
      out.write("                      <nav class=\"nav-item\"><a href=\"#\" class=\"nav-link\">Home</a></nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"p-2\">\r\n");
      out.write("                      <nav class=\"nav-item\"><a href=\"#\" class=\"nav-link\">All products</a></nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"p-2\">\r\n");
      out.write("                      <div class=\" \">\r\n");
      out.write("                        <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#collapseHome3\" role=\"button\" aria-expanded=\"false\" aria-controls=\"collapseHome\">\r\n");
      out.write("                        Tops <span class=\"ps-2 small\"><i class=\"fa-solid fa-chevron-down\"></i></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"collapse\" id=\"collapseHome3\">\r\n");
      out.write("                          <div class=\"card card-body\">\r\n");
      out.write("                            <ul class=\"list-unstyled\">\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Floweral Tops</a></li>\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Cropped Tops</a></li>\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Tops</a></li>\r\n");
      out.write("                             </ul>\r\n");
      out.write("                           </div>\r\n");
      out.write("                         </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                   \r\n");
      out.write("                    <div class=\"p-2\">\r\n");
      out.write("                      <li class=\"nav-item\">\r\n");
      out.write("                      <a class=\"nav-link \" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                      Co-ords\r\n");
      out.write("                      </a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   \r\n");
      out.write("                    <div class=\"p-2\">\r\n");
      out.write("                      <div class=\"\">\r\n");
      out.write("                        <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#collapseHome2\" role=\"button\" aria-expanded=\"false\" aria-controls=\"collapseHome\">\r\n");
      out.write("                        Exclusive <span class=\"ps-2 small\"><i class=\"fa-solid fa-chevron-down\"></i></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"collapse\" id=\"collapseHome2\">\r\n");
      out.write("                          <div class=\"card card-body\">\r\n");
      out.write("                            <ul class=\"list-unstyled\">\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Tops</a></li>\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Shorts</a></li>\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Dresses</a></li>\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Denimes</a></li>\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Jumpsuit</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>  \r\n");
      out.write("                    <div class=\"p-2\">\r\n");
      out.write("                      <div class=\"\">\r\n");
      out.write("                       \r\n");
      out.write("                        <a class=\"nav-link\" data-bs-toggle=\"collapse\" href=\"#collapseHome1\" role=\"button\" aria-expanded=\"false\" aria-controls=\"collapseHome\">\r\n");
      out.write("                          New In <span class=\"ps-2 small\"><i class=\"fa-solid fa-chevron-down\"></i></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"collapse\" id=\"collapseHome1\">\r\n");
      out.write("                          <div class=\"card card-body\">\r\n");
      out.write("                            <ul class=\"list-unstyled\">\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Tops</a></li>\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Shorts</a></li>\r\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"#\">Denimes</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>  \r\n");
      out.write("                      \r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("             \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("		   \r\n");
      out.write("		   \r\n");
      out.write("		  \r\n");
      out.write("  </div>\r\n");
      out.write(" </header>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("   </div>    \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("   <!--aside section  -->\r\n");
      out.write("    <aside class=\"sidebar  \" id=\"product-sidebar\">\r\n");
      out.write("        <div class=\"offcanvas offcanvas-start\" data-bs-scroll=\"true\" data-bs-backdrop=\"false\" id=\"bd-sidebar\" tabindex=\"-1\"    aria-labelledby=\"offcanvasScrollingLabel\">\r\n");
      out.write("          <div class=\"offcanvas-header d-sm-none\">\r\n");
      out.write("            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"offcanvas-body\">\r\n");
      out.write("            <div class=\"list-group \">\r\n");
      out.write("              <a href=\"#\" class=\"list-group-item main d-flex justify-content-between \" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseExample\"role=\"button\" aria-expanded=\"false\" aria-controls=\"collapseExample\">\r\n");
      out.write("                Categories\r\n");
      out.write("                <span><i class=\"fa-solid fa-chevron-down\"></i></span>\r\n");
      out.write("              </a>\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"collapse\" id=\"collapseExample\">\r\n");
      out.write("                <div class=\"card card-body\">\r\n");
      out.write("                  <ul class=\"list-group\">\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"list-group color\">\r\n");
      out.write("              <a href=\"#\" class=\"list-group-item main d-flex justify-content-between \" data-bs-toggle=\"collapse\" data-bs-target=\"#color-list\"role=\"button\" aria-expanded=\"false\" aria-controls=\"color-list\">\r\n");
      out.write("                Color\r\n");
      out.write("                <span><i class=\"fa-solid fa-chevron-down\"></i></span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <div>\r\n");
      out.write("                <div class=\"collapse\" id=\"color-list\">\r\n");
      out.write("                 <div class=\"card card-body\">\r\n");
      out.write("                   <ul class=\"list-group\">\r\n");
      out.write("                       ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                   </ul>\r\n");
      out.write("                 </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"list-group price\">\r\n");
      out.write("              <a href=\"#\" class=\"list-group-item  main d-flex justify-content-between\" data-bs-toggle=\"collapse\" data-bs-target=\"#price-list\"role=\"button\" aria-expanded=\"false\" aria-controls=\"price-list\">\r\n");
      out.write("                Price\r\n");
      out.write("                <span><i class=\"fa-solid fa-chevron-down\"></i></span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"\">\r\n");
      out.write("                <div class=\"collapse\" id=\"price-list\">\r\n");
      out.write("                  <div class=\"card card-body\">\r\n");
      out.write("                    <ul class=\"list-group\">\r\n");
      out.write("                     <li class=\"list-group-item\">\r\n");
      out.write("                       <div class=\"checkbox\">\r\n");
      out.write("                         <label>\r\n");
      out.write("                           <input type=\"checkbox\" name=\"\" value=\"500-1000\" class=\"price-filter\">\r\n");
      out.write("                           <span>500-1000</span>\r\n");
      out.write("                         </label>\r\n");
      out.write("                       </div>\r\n");
      out.write("                       \r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"list-group-item\">\r\n");
      out.write("                       <div class=\"checkbox\">\r\n");
      out.write("                         <label>\r\n");
      out.write("                           <input type=\"checkbox\" name=\"\" value=\"1000-2500\" class=\"price-filter\">\r\n");
      out.write("                           <span>1000-2500</span>\r\n");
      out.write("                         </label>\r\n");
      out.write("                       </div>\r\n");
      out.write("                       \r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"list-group-item\">\r\n");
      out.write("                       <div class=\"checkbox\">\r\n");
      out.write("                         <label>\r\n");
      out.write("                           <input type=\"checkbox\" name=\"\" value=\"2500-4000\" class=\"price-filter\">\r\n");
      out.write("                           <span>2500-4000</span>\r\n");
      out.write("                         </label>\r\n");
      out.write("                       </div>\r\n");
      out.write("                       \r\n");
      out.write("                     </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </aside>\r\n");
      out.write("    \r\n");
      out.write("    <!--product section  -->\r\n");
      out.write("     <section>\r\n");
      out.write("      <div class=\"container-fluid \" id=\"product-container\">\r\n");
      out.write("        <div class=\"mt-2 ms-2 d-flex align-items-center\" id=\"product-count\">\r\n");
      out.write("          ");
 if(category == null && searchedQuery != null){ 
      out.write("\r\n");
      out.write("          <h6>");
      out.print( "Top Search Results For "+ searchedQuery );
      out.write("</h6>\r\n");
      out.write("          ");
 }else {
      out.write("\r\n");
      out.write("          <h3>");
      out.print(category.equals("all")?"All Products": category );
      out.write("</h3>\r\n");
      out.write("          ");
} 
      out.write("\r\n");
      out.write("          <span class=\"ps-2\" id=\"totalProductCount\">(");
      out.print(list.size() );
      out.write(")</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row row-cols-lg-5 row-cols-md-4 row-cols-sm-3 row-cols-2 g-2 g-lg-3 g-4 mt-2\">\r\n");
      out.write("           ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- sticky filters -->\r\n");
      out.write("    <div class=\"container-fluid position-fixed bottom-0 d-sm-none  d-flex\">\r\n");
      out.write("      <div class=\"col-6\">\r\n");
      out.write("          <button class=\"btn btn-success w-100\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#bd-sidebar\" aria-controls=\"offcanvasScrolling\">\r\n");
      out.write("             <span class=\"fs-5\"><i class=\"fa-solid fa-arrow-down-wide-short\"></i></span>\r\n");
      out.write("          </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-6\">\r\n");
      out.write("          <button class=\"btn btn-success w-100\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#bd-sidebar\" aria-controls=\"offcanvasScrolling\">\r\n");
      out.write("              <span class=\"fs-5\"><i class=\"fa-solid fa-sliders\"></i></span>\r\n");
      out.write("          </button>\r\n");
      out.write("      </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<footer class=\"footer pt-lg-5 pt-4 position-sticky bootom-0\">\r\n");
      out.write("  <div class=\" bg-light\" id=\"footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("       <div class=\"row py-4\">\r\n");
      out.write("       <div class=\"col-lg-4 col-md-12 col-12 mb-sm-4 \">\r\n");
      out.write("         <h6 class=\"mb-2 px-3\">Categories</h6>\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("           <div class=\"col-6 \">\r\n");
      out.write("             <ul class=\"nav flex-column\">\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Athleisure </a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Skirts </a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Skorts</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Crop Tops </a></li>\r\n");
      out.write("             </ul>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"col-6\">\r\n");
      out.write("                <!-- list -->\r\n");
      out.write("              <ul class=\"nav flex-column\">\r\n");
      out.write("                <li class=\"nav-item mb-0 \"><a href=\"#!\" class=\"nav-link\">Dresses</a></li>\r\n");
      out.write("                <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Tops </a></li>\r\n");
      out.write("                <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Shirts  </a></li>\r\n");
      out.write("                <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Jackets</a></li>\r\n");
      out.write("                <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Bottomwear </a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("               \r\n");
      out.write("           </div>\r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"col-12 col-lg-8 col-md-12\">\r\n");
      out.write("         <div class=\"row \">\r\n");
      out.write("           <div class=\"col-12 col-sm-12 col-md-3 pb-2 pb-md-0\">\r\n");
      out.write("             <h6 class=\"mb-2 px-3\">Shop By Colors</h6>\r\n");
      out.write("             <ul class=\"nav flex-column \">\r\n");
      out.write("               <li class=\"nav-item mb-0 \"><a href=\"#!\" class=\"nav-link\">Pink Dresses</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0 \"><a href=\"#!\" class=\"nav-link\">Red Tops</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#1\" class=\"nav-link\">Blog</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Blue Tops</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Yellow Tops</a></li>\r\n");
      out.write("             </ul>\r\n");
      out.write("           </div> \r\n");
      out.write("           <div class=\"col-6 col-sm-6 col-md-3 pb-2 pb-md-0\">\r\n");
      out.write("             <h6 class=\"mb-2 px-3\">For Consumers</h6>\r\n");
      out.write("             <ul class=\"nav flex-column\">\r\n");
      out.write("                   <!-- list -->\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Payments</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Shipping</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Product Returns</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">FAQ</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"./pages/shop-checkout.html\" class=\"nav-link\">Shop Checkout</a></li>\r\n");
      out.write("             </ul>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"col-6 col-sm-6 col-md-3 pb-2 pb-md-0\">\r\n");
      out.write("             <h6 class=\"mb-2 px-3\">Contact Us</h6>    \r\n");
      out.write("             <ul class=\"nav flex-column\">\r\n");
      out.write("                 <!-- list -->\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Find a Store </a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Size Guide</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Track Order</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">FAQ</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">E-GIFT VOUCHER</a></li>\r\n");
      out.write("             </ul>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"col-6 col-sm-6 col-md-3 pb-2 pb-md-0\">\r\n");
      out.write("             <h6 class=\"mb-2 px-3\">Corporate Info</h6>   \r\n");
      out.write("             <ul class=\"nav flex-column\">\r\n");
      out.write("                 <!-- list -->\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">About Us</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">About Bestseller</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Promos &amp; Coupons</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">Privacy policy</a></li>\r\n");
      out.write("               <li class=\"nav-item mb-0\"><a href=\"#!\" class=\"nav-link\">T&C</a></li>\r\n");
      out.write("             </ul>\r\n");
      out.write("           </div>\r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"border-top py-4\">\r\n");
      out.write("       <div class=\"row\">\r\n");
      out.write("         <div class=\"col-lg-5\">\r\n");
      out.write("           <ul>\r\n");
      out.write("             <li class=\"list-inline-item text-dark\">Payment Partners</li>\r\n");
      out.write("             <li class=\"list-inline-item\"><a href=\"!#\"><img src=\"images/footer/amazonpay.svg\" alt=\"amazon logo\"></a>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"list-inline-item\">\r\n");
      out.write("               <a href=\"!#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/footer/american-express.svg\" alt=\"\"></a>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"list-inline-item\">\r\n");
      out.write("               <a href=\"#!\"><img src=\"images/footer/paypal.svg\" alt=\"\"></a>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"list-inline-item\">\r\n");
      out.write("               <a href=\"#!\"><img src=\"images/footer/mastercard.svg\" alt=\"\"></a>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"list-inline-item\">\r\n");
      out.write("               <a href=\"#!\"><img src=\"images/footer/visa.svg\" alt=\"\"></a>\r\n");
      out.write("             </li>\r\n");
      out.write("           </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"col-lg-7 \">\r\n");
      out.write("            <ul class=\"list-inline mb-0 text-lg-end text-center\">\r\n");
      out.write("             <li class=\"list-inline-item mb-0  text-dark\">Get deliveries with FreshCart</li>\r\n");
      out.write("             <li class=\"list-inline-item ms-4\">\r\n");
      out.write("               <a href=\"#!\"> <img src=\"images/footer/appstore-btn.svg\" alt=\"\" style=\"width: 140px;\"></a></li>\r\n");
      out.write("             <li class=\"list-inline-item\">\r\n");
      out.write("               <a href=\"#!\"> <img src=\"images/footer/googleplay-btn.svg\" alt=\"\" style=\"width: 140px;\"></a></li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"border-top py-4\">\r\n");
      out.write("       <div class=\"d-flex justify-content-center \" id=\"social_media\">\r\n");
      out.write("         <div class=\"text-muted\"><small><p class=\"px-2 d-inline\">Follow us on</p>\r\n");
      out.write("          <li class=\"list-inline-item px-0\">\r\n");
      out.write("            <a href=\"!#\" class=\"fs-4 \">\r\n");
      out.write("              <i class=\"fa-brands fa-facebook\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("         <li class=\"list-inline-item\">\r\n");
      out.write("            <a href=\"!#\" class=\"fs-4 \">\r\n");
      out.write("              <i class=\"fa-brands fa-instagram\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("         <li class=\"list-inline-item\">\r\n");
      out.write("            <a href=\"!#\" class=\"fs-4 \">\r\n");
      out.write("              <i class=\"fa-brands fa-x-twitter\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("         </small> \r\n");
      out.write(" \r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   \r\n");
      out.write("   let checkboxes = document.querySelectorAll(\".color-filter\");\r\n");
      out.write("  \r\n");
      out.write("   checkboxes.forEach((checkbox)=>{\r\n");
      out.write("	    checkbox.addEventListener(\"change\",filterProducts)\r\n");
      out.write("	});\r\n");
      out.write("   function filterProducts(){\r\n");
      out.write("	   let selectedColors = Array.from(checkboxes)\r\n");
      out.write("	                             .filter((checkbox)=>checkbox.checked)\r\n");
      out.write("	                             .map((checkbox)=> checkbox.value)\r\n");
      out.write("	                             \r\n");
      out.write("\r\n");
      out.write("	  let productCards = document.querySelectorAll(\".product-card\");  \r\n");
      out.write("	   productCards.forEach((card)=>{\r\n");
      out.write("		   let productColors = card.dataset.colors ? card.dataset.colors.split(\",\") : [];\r\n");
      out.write("		   let isvisible = selectedColors.lenght === 0 || selectedColors.some((color)=> productColors.includes(color));\r\n");
      out.write("		   card.style.display = isvisible? \"\" : \"none\";\r\n");
      out.write("		 \r\n");
      out.write("	   });\r\n");
      out.write("	   \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   let priceCheckboxes = document.querySelectorAll(\".price-filter\");\r\n");
      out.write("   console.log(priceCheckboxes)\r\n");
      out.write("   priceCheckboxes.forEach((checkbox)=>{\r\n");
      out.write("	   checkbox.addEventListener(\"change\",filterProducPrice)\r\n");
      out.write("   })\r\n");
      out.write("   \r\n");
      out.write("   function filterProducPrice(){\r\n");
      out.write("	   let selectedPriceRange = Array.from(priceCheckboxes)\r\n");
      out.write("	                                 .filter((checkbox)=>checkbox.checked)\r\n");
      out.write("	                                 .map((checkbox)=> checkbox.value)\r\n");
      out.write("	                                 .map((range)=>String(range).split(\"-\"))\r\n");
      out.write("	                                 .flat();\r\n");
      out.write("	                                 \r\n");
      out.write("	                  \r\n");
      out.write("	                     \r\n");
      out.write("	   const maxPrice = Math.max(...selectedPriceRange)\r\n");
      out.write("	   const minPrice = Math.min(...selectedPriceRange);\r\n");
      out.write("	   let productCards = document.querySelectorAll(\".product-card\"); \r\n");
      out.write("	   productCards.forEach((card)=>{\r\n");
      out.write("		   let productPrice = card.dataset.price;\r\n");
      out.write("		   let isvisible = selectedPriceRange.length === 0 || productPrice >= minPrice && maxPrice >= productPrice;\r\n");
      out.write("		   card.style.display = isvisible? \"\" : \"none\";\r\n");
      out.write("		   \r\n");
      out.write("	   })\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /product.jsp(79,20) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/product.jsp(79,20) '${catList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${catList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /product.jsp(79,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("cat");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                       <li class=\"list-group-item\"><a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/product.jsp?category=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cat.getCategory_name()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cat.getCategory_name()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></li>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /product.jsp(96,23) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/product.jsp(96,23) '${colors}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${colors}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /product.jsp(96,23) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("color");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                          <li class=\"list-group-item\">\r\n");
            out.write("						       <div class=\"checkbox\">\r\n");
            out.write("						            <label>\r\n");
            out.write("						               <input type=\"checkbox\" name=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${color}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${color}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"color-filter\">\r\n");
            out.write("						               <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${color}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("						            </label>\r\n");
            out.write("						         </div>\r\n");
            out.write("		                      \r\n");
            out.write("		                    </li> \r\n");
            out.write("                      ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /product.jsp(172,11) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/product.jsp(172,11) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /product.jsp(172,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("product");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("             <div class=\"col product-card\" data-colors=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getProduct_color()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-price=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getProduct_price() }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                     <div class=\"card\" >\r\n");
            out.write("				        <div class=\"card-body\">\r\n");
            out.write("				            <div class=\"text-start position-relative mb-2\">\r\n");
            out.write("				                <a href=\"#\"><img src=\"img/product/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getImage()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"product-image\" class=\"img-fluid image-container\" >\r\n");
            out.write("				                </a>\r\n");
            out.write("				                <div class=\"product-action d-flex justify-content-center mt-5 gap-1 position-absolute  \" tabindex=\"-1\" id=\"little-navigation\">\r\n");
            out.write("				                    <a href=\"#\" class=\"px-2 btn \" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" aria-label=\"Quick View\" data-bs-original-title=\"Quick View\"><i class=\"fa-regular fa-eye\" aria-hidden=\"true\"></i></a>\r\n");
            out.write("				                    <a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/function/saveWishlist.jsp?action=save&product_id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getId()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"px-2 btn \" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" aria-label=\"Whishlist\" data-bs-original-title=\"Whishlist\"><i class=\"fa-regular fa-heart\" aria-hidden=\"true\"></i></a>\r\n");
            out.write("				                    <a href=\"#\" class=\"px-2 btn \" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" aria-label=\"Compare\" data-bs-original-title=\"Compare\"><i class=\"fa-solid fa-arrow-right-arrow-left\" aria-hidden=\"true\"></i></a>\r\n");
            out.write("				                 </div>\r\n");
            out.write("				               \r\n");
            out.write("				              </div>\r\n");
            out.write("				            <h6 class=\" lh-sm \"><a href=\"#\" class=\"fs-6 text-decoration-none :hover-up text-truncate pb-0 mb-0\" style=\"max-width: 200px;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Reduce.reduceDesc(product.getProduct_name())}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a><h6>\r\n");
            out.write("				                <div class=\"mt-0 pt-0 text-start lh-sm \">\r\n");
            out.write("				                    <div class=\"small\">\r\n");
            out.write("				                      <small>\r\n");
            out.write("				                          <i class=\" fa-solid fa-star text-warning\" style=\"font-size: 12px;\" aria-hidden=\"true\"></i>\r\n");
            out.write("				                          <i class=\" fa-solid fa-star text-warning\" style=\"font-size: 12px;\" aria-hidden=\"true\"></i>\r\n");
            out.write("				                          <i class=\" fa-solid fa-star text-warning\" style=\"font-size: 12px;\" aria-hidden=\"true\"></i>\r\n");
            out.write("				                          <i class=\" fa-solid fa-star text-warning\" style=\"font-size: 12px;\" aria-hidden=\"true\"></i>\r\n");
            out.write("				                          <i class=\" fa-solid fa-star-half-stroke text-warning\" style=\"font-size: 12px;\" aria-hidden=\"true\"></i>\r\n");
            out.write("				                          <span  style=\"font-size: 12px;\" id=\"total-star\">4.5</span>\r\n");
            out.write("				                      </small>\r\n");
            out.write("				                      \r\n");
            out.write("				                    </div>\r\n");
            out.write("				                </div>\r\n");
            out.write("				                <div class=\"d-flex justify-content-between align-items-center \">\r\n");
            out.write("				                    <div>\r\n");
            out.write("				                        <span class=\" me-1\" id=\"price\">&#8377;");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getProduct_price()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("				                        <span class=\"text-decoration-line-through\" id=\"original-price\">&#8377;");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getOriginal_price()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("				        \r\n");
            out.write("				                    </div>\r\n");
            out.write("				                    <div class=\"d-grid mt-2\">\r\n");
            out.write("				                        <a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/addToCart/saveCart.jsp?action=save&product_id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getId()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn btn-dark text-light d-flex align-items-center gap-1\">\r\n");
            out.write("				                           <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-plus\">\r\n");
            out.write("				                              <line x1=\"12\" y1=\"5\" x2=\"12\" y2=\"19\"></line>\r\n");
            out.write("				                              <line x1=\"5\" y1=\"12\" x2=\"19\" y2=\"12\"></line>\r\n");
            out.write("				                           </svg>\r\n");
            out.write("				                           Add \r\n");
            out.write("				                        </a>\r\n");
            out.write("				                     </div>\r\n");
            out.write("				                </div>\r\n");
            out.write("				        </div>\r\n");
            out.write("			      </div>\r\n");
            out.write("             </div>\r\n");
            out.write("           ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
